import { MediaItem, MediaType } from "./types";
import { moodsFromGenres } from "./genres";

export interface RawItem {
  id: number;
  type: MediaType;
  title: string;
  year: number;
  overview: string;
  genres: string[];
  rating: number;
  voteCount: number;
  popularity: number; // 0-100
  language: string;
  originalLanguage: string;
  country?: string;
  runtime?: number | null;
  seasons?: number | null;
  episodes?: number | null;
  director?: string;
  cast?: string[];
}

// A hand-curated spread of genuinely acclaimed and popular titles across genre,
// decade, and country, used as realistic offline data when TMDB_API_KEY is unset.
export const RAW_CATALOG: RawItem[] = [
  { id: 1, type: "movie", title: "Interstellar", year: 2014, overview: "A crew of explorers travels through a wormhole in search of a new home for humanity as Earth runs out of time.", genres: ["Sci-Fi", "Drama", "Adventure"], rating: 8.6, voteCount: 34000, popularity: 92, language: "English", originalLanguage: "en", runtime: 169, director: "Christopher Nolan", cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"] },
  { id: 2, type: "tv", title: "Dark", year: 2017, overview: "The disappearance of children in a small German town uncovers a web of time travel connecting four families across generations.", genres: ["Mystery", "Sci-Fi", "Thriller", "Drama"], rating: 8.7, voteCount: 15000, popularity: 84, language: "German", originalLanguage: "de", seasons: 3, episodes: 26, director: "Baran bo Odar", cast: ["Louis Hofmann", "Karoline Eichhorn"] },
  { id: 3, type: "tv", title: "Breaking Bad", year: 2008, overview: "A chemistry teacher turned methamphetamine manufacturer descends deeper into the criminal underworld to secure his family's future.", genres: ["Crime", "Drama", "Thriller"], rating: 8.9, voteCount: 45000, popularity: 90, language: "English", originalLanguage: "en", seasons: 5, episodes: 62, director: "Vince Gilligan", cast: ["Bryan Cranston", "Aaron Paul"] },
  { id: 4, type: "movie", title: "Parasite", year: 2019, overview: "A poor family cons its way into working for a wealthy household, setting off a chain of events no one could have foreseen.", genres: ["Drama", "Thriller", "Comedy"], rating: 8.5, voteCount: 20000, popularity: 88, language: "Korean", originalLanguage: "ko", runtime: 132, director: "Bong Joon-ho", cast: ["Song Kang-ho", "Lee Sun-kyun"] },
  { id: 5, type: "movie", title: "Spirited Away", year: 2001, overview: "A young girl wanders into a spirit world and must work in a bathhouse for gods to find her way back to the human world.", genres: ["Animation", "Fantasy", "Family", "Adventure"], rating: 8.6, voteCount: 16000, popularity: 80, language: "Japanese", originalLanguage: "ja", runtime: 125, director: "Hayao Miyazaki", cast: ["Rumi Hiiragi"] },
  { id: 6, type: "movie", title: "The Grand Budapest Hotel", year: 2014, overview: "A legendary concierge and his loyal lobby boy become entangled in a theft, a will, and a chase across a fictional European republic.", genres: ["Comedy", "Adventure", "Drama"], rating: 8.1, voteCount: 14000, popularity: 70, language: "English", originalLanguage: "en", runtime: 100, director: "Wes Anderson", cast: ["Ralph Fiennes", "Tony Revolori"] },
  { id: 7, type: "movie", title: "Amélie", year: 2001, overview: "A shy Parisian waitress secretly orchestrates small acts of kindness that ripple through the lives of everyone around her.", genres: ["Romance", "Comedy", "Drama"], rating: 8.3, voteCount: 12000, popularity: 62, language: "French", originalLanguage: "fr", runtime: 122, director: "Jean-Pierre Jeunet", cast: ["Audrey Tautou"] },
  { id: 8, type: "tv", title: "The Office", year: 2005, overview: "A mockumentary following the everyday absurdities of the staff at a mid-sized paper company in Scranton, Pennsylvania.", genres: ["Comedy"], rating: 8.8, voteCount: 32000, popularity: 87, language: "English", originalLanguage: "en", seasons: 9, episodes: 201, director: "Greg Daniels", cast: ["Steve Carell", "Rainn Wilson"] },
  { id: 9, type: "movie", title: "Get Out", year: 2017, overview: "A young man's visit to his girlfriend's family estate reveals a horrifying secret hiding beneath their liberal hospitality.", genres: ["Horror", "Thriller", "Mystery"], rating: 7.7, voteCount: 21000, popularity: 75, language: "English", originalLanguage: "en", runtime: 104, director: "Jordan Peele", cast: ["Daniel Kaluuya", "Allison Williams"] },
  { id: 10, type: "movie", title: "La La Land", year: 2016, overview: "A jazz pianist and an aspiring actress fall in love in Los Angeles while chasing their creative dreams.", genres: ["Musical", "Romance", "Drama", "Comedy"], rating: 8.0, voteCount: 19000, popularity: 79, language: "English", originalLanguage: "en", runtime: 128, director: "Damien Chazelle", cast: ["Ryan Gosling", "Emma Stone"] },
  { id: 11, type: "movie", title: "The Dark Knight", year: 2008, overview: "Batman raises the stakes in his war on crime as the Joker unleashes chaos on Gotham City.", genres: ["Action", "Crime", "Drama", "Thriller"], rating: 9.0, voteCount: 40000, popularity: 95, language: "English", originalLanguage: "en", runtime: 152, director: "Christopher Nolan", cast: ["Christian Bale", "Heath Ledger"] },
  { id: 12, type: "movie", title: "Whiplash", year: 2014, overview: "A driven young drummer enrolls at a cutthroat music conservatory under an instructor who will stop at nothing to extract greatness.", genres: ["Drama", "Musical"], rating: 8.5, voteCount: 15000, popularity: 68, language: "English", originalLanguage: "en", runtime: 106, director: "Damien Chazelle", cast: ["Miles Teller", "J.K. Simmons"] },
  { id: 13, type: "movie", title: "Coco", year: 2017, overview: "A boy with a forbidden love of music journeys into the Land of the Dead to uncover the truth about his family's history.", genres: ["Animation", "Family", "Fantasy", "Musical"], rating: 8.4, voteCount: 18000, popularity: 76, language: "English", originalLanguage: "en", runtime: 105, director: "Lee Unkrich", cast: ["Anthony Gonzalez"] },
  { id: 14, type: "tv", title: "Money Heist", year: 2017, overview: "A criminal mastermind assembles a team of specialists to pull off the largest heist in Spanish history.", genres: ["Crime", "Thriller", "Drama"], rating: 8.2, voteCount: 22000, popularity: 83, language: "Spanish", originalLanguage: "es", seasons: 5, episodes: 41, director: "Álex Pina", cast: ["Úrsula Corberó", "Álvaro Morte"] },
  { id: 15, type: "movie", title: "City of God", year: 2002, overview: "Two boys growing up in a violent Rio de Janeiro slum take radically different paths, one toward crime, the other toward art.", genres: ["Crime", "Drama"], rating: 8.6, voteCount: 12500, popularity: 60, language: "Portuguese", originalLanguage: "pt", runtime: 130, director: "Fernando Meirelles", cast: ["Alexandre Rodrigues"] },
  { id: 16, type: "movie", title: "Everything Everywhere All at Once", year: 2022, overview: "An overwhelmed laundromat owner discovers she must connect with parallel versions of herself to save the multiverse.", genres: ["Sci-Fi", "Comedy", "Action", "Fantasy"], rating: 7.9, voteCount: 17000, popularity: 82, language: "English", originalLanguage: "en", runtime: 140, director: "Daniel Kwan, Daniel Scheinert", cast: ["Michelle Yeoh", "Ke Huy Quan"] },
  { id: 17, type: "tv", title: "Chernobyl", year: 2019, overview: "A dramatization of the 1986 nuclear disaster and the sacrifices made by those who fought to contain its fallout.", genres: ["Drama", "Historical", "Thriller"], rating: 9.3, voteCount: 21000, popularity: 78, language: "English", originalLanguage: "en", seasons: 1, episodes: 5, director: "Johan Renck", cast: ["Jared Harris", "Stellan Skarsgård"] },
  { id: 18, type: "movie", title: "Seven Samurai", year: 1954, overview: "A poor farming village hires seven ronin to defend it from marauding bandits ahead of the annual harvest.", genres: ["Action", "Adventure", "Drama"], rating: 8.6, voteCount: 3600, popularity: 30, language: "Japanese", originalLanguage: "ja", runtime: 207, director: "Akira Kurosawa", cast: ["Toshiro Mifune"] },
  { id: 19, type: "movie", title: "Casablanca", year: 1942, overview: "An American expatriate running a nightclub in Vichy-controlled Morocco must choose between love and duty when his past walks back in.", genres: ["Romance", "Drama", "War"], rating: 8.5, voteCount: 5900, popularity: 35, language: "English", originalLanguage: "en", runtime: 102, director: "Michael Curtiz", cast: ["Humphrey Bogart", "Ingrid Bergman"] },
  { id: 20, type: "movie", title: "Pulp Fiction", year: 1994, overview: "The lives of two hitmen, a boxer, and a gangster's wife intertwine in a nonlinear tale of violence and redemption.", genres: ["Crime", "Drama"], rating: 8.9, voteCount: 26000, popularity: 85, language: "English", originalLanguage: "en", runtime: 154, director: "Quentin Tarantino", cast: ["John Travolta", "Samuel L. Jackson"] },
  { id: 21, type: "movie", title: "Spider-Man: Into the Spider-Verse", year: 2018, overview: "A teenager from Brooklyn becomes Spider-Man and teams up with counterparts from parallel dimensions to save them all.", genres: ["Animation", "Action", "Adventure", "Sci-Fi"], rating: 8.4, voteCount: 15000, popularity: 81, language: "English", originalLanguage: "en", runtime: 117, director: "Bob Persichetti, Peter Ramsey", cast: ["Shameik Moore"] },
  { id: 22, type: "movie", title: "The Shawshank Redemption", year: 1994, overview: "A banker wrongly convicted of murder forms an unlikely friendship with a fellow inmate over decades in Shawshank prison.", genres: ["Drama"], rating: 9.3, voteCount: 28000, popularity: 93, language: "English", originalLanguage: "en", runtime: 142, director: "Frank Darabont", cast: ["Tim Robbins", "Morgan Freeman"] },
  { id: 23, type: "movie", title: "Your Name.", year: 2016, overview: "Two teenagers, a boy in Tokyo and a girl in the countryside, mysteriously begin swapping bodies and racing against time to meet.", genres: ["Animation", "Romance", "Fantasy", "Drama"], rating: 8.4, voteCount: 11000, popularity: 65, language: "Japanese", originalLanguage: "ja", runtime: 106, director: "Makoto Shinkai", cast: ["Ryunosuke Kamiki"] },
  { id: 24, type: "tv", title: "Fleabag", year: 2016, overview: "A grief-stricken, sharp-witted young woman navigates modern life in London while breaking the fourth wall about it.", genres: ["Comedy", "Drama"], rating: 8.7, voteCount: 8000, popularity: 58, language: "English", originalLanguage: "en", seasons: 2, episodes: 12, director: "Phoebe Waller-Bridge", cast: ["Phoebe Waller-Bridge"] },
  { id: 25, type: "movie", title: "Mad Max: Fury Road", year: 2015, overview: "In a post-apocalyptic wasteland, a rebel warrior helps a woman lead a group of escaped captives away from a tyrannical warlord.", genres: ["Action", "Adventure", "Sci-Fi"], rating: 8.1, voteCount: 22000, popularity: 84, language: "English", originalLanguage: "en", runtime: 120, director: "George Miller", cast: ["Tom Hardy", "Charlize Theron"] },
  { id: 26, type: "movie", title: "Portrait of a Lady on Fire", year: 2019, overview: "An 18th-century painter falls for the reluctant bride-to-be she has been secretly commissioned to portray.", genres: ["Romance", "Drama", "Historical"], rating: 8.1, voteCount: 5300, popularity: 45, language: "French", originalLanguage: "fr", runtime: 122, director: "Céline Sciamma", cast: ["Noémie Merlant", "Adèle Haenel"] },
  { id: 27, type: "tv", title: "Stranger Things", year: 2016, overview: "A group of kids in a small Indiana town uncover a government conspiracy and a monstrous parallel dimension.", genres: ["Sci-Fi", "Horror", "Adventure", "Drama"], rating: 8.6, voteCount: 24000, popularity: 89, language: "English", originalLanguage: "en", seasons: 4, episodes: 42, director: "The Duffer Brothers", cast: ["Millie Bobby Brown", "Finn Wolfhard"] },
  { id: 28, type: "movie", title: "Knives Out", year: 2019, overview: "A famous crime novelist's death brings a colorful family and a brilliant detective together for a modern whodunit.", genres: ["Mystery", "Comedy", "Crime"], rating: 7.9, voteCount: 17000, popularity: 74, language: "English", originalLanguage: "en", runtime: 130, director: "Rian Johnson", cast: ["Daniel Craig", "Ana de Armas"] },
  { id: 29, type: "movie", title: "Oldboy", year: 2003, overview: "A man imprisoned without explanation for fifteen years is suddenly released and given five days to find out why.", genres: ["Thriller", "Mystery", "Drama"], rating: 8.4, voteCount: 8500, popularity: 55, language: "Korean", originalLanguage: "ko", runtime: 120, director: "Park Chan-wook", cast: ["Choi Min-sik"] },
  { id: 30, type: "movie", title: "Toy Story", year: 1995, overview: "A cowboy doll's world is turned upside down when a flashy space ranger toy arrives and steals his owner's affection.", genres: ["Animation", "Family", "Comedy", "Adventure"], rating: 8.3, voteCount: 18000, popularity: 78, language: "English", originalLanguage: "en", runtime: 81, director: "John Lasseter", cast: ["Tom Hanks", "Tim Allen"] },
  { id: 31, type: "tv", title: "The Crown", year: 2016, overview: "A sweeping chronicle of Queen Elizabeth II's reign, from her wedding through decades of political and personal upheaval.", genres: ["Drama", "Historical"], rating: 8.6, voteCount: 12000, popularity: 66, language: "English", originalLanguage: "en", seasons: 6, episodes: 60, director: "Peter Morgan", cast: ["Claire Foy", "Olivia Colman"] },
  { id: 32, type: "movie", title: "The Silence of the Lambs", year: 1991, overview: "A young FBI trainee seeks the help of an imprisoned cannibalistic killer to catch another serial murderer.", genres: ["Thriller", "Horror", "Crime"], rating: 8.6, voteCount: 15000, popularity: 71, language: "English", originalLanguage: "en", runtime: 118, director: "Jonathan Demme", cast: ["Jodie Foster", "Anthony Hopkins"] },
  { id: 33, type: "movie", title: "Life Is Beautiful", year: 1997, overview: "A father uses humor and imagination to shield his young son from the horrors of a Nazi concentration camp.", genres: ["Drama", "Comedy", "War"], rating: 8.6, voteCount: 12000, popularity: 52, language: "Italian", originalLanguage: "it", runtime: 116, director: "Roberto Benigni", cast: ["Roberto Benigni"] },
  { id: 34, type: "tv", title: "Planet Earth II", year: 2016, overview: "A landmark nature documentary series capturing wildlife across the planet's most extreme and remote habitats.", genres: ["Documentary"], rating: 9.5, voteCount: 8600, popularity: 60, language: "English", originalLanguage: "en", seasons: 1, episodes: 6, director: "David Attenborough", cast: ["David Attenborough"] },
  { id: 35, type: "movie", title: "Titanic", year: 1997, overview: "A penniless artist and a young aristocrat fall in love aboard the ill-fated maiden voyage of an ocean liner.", genres: ["Romance", "Drama"], rating: 7.9, voteCount: 24000, popularity: 82, language: "English", originalLanguage: "en", runtime: 195, director: "James Cameron", cast: ["Leonardo DiCaprio", "Kate Winslet"] },
  { id: 36, type: "movie", title: "The Grand Illusion", year: 1937, overview: "French officers held in a German POW camp during WWI plot escape while class and nationality complicate loyalty.", genres: ["War", "Drama"], rating: 8.1, voteCount: 1200, popularity: 15, language: "French", originalLanguage: "fr", runtime: 114, director: "Jean Renoir", cast: ["Jean Gabin"] },
  { id: 37, type: "tv", title: "True Detective", year: 2014, overview: "Two detectives are drawn back into a case they investigated years earlier, unraveling a web of occult crime in Louisiana.", genres: ["Crime", "Mystery", "Drama"], rating: 8.9, voteCount: 14000, popularity: 68, language: "English", originalLanguage: "en", seasons: 4, episodes: 27, director: "Nic Pizzolatto", cast: ["Matthew McConaughey", "Woody Harrelson"] },
  { id: 38, type: "movie", title: "Blade Runner 2049", year: 2017, overview: "A new blade runner unearths a secret that could plunge what's left of society into chaos, leading him to a former blade runner in hiding.", genres: ["Sci-Fi", "Thriller", "Drama"], rating: 8.0, voteCount: 14500, popularity: 73, language: "English", originalLanguage: "en", runtime: 164, director: "Denis Villeneuve", cast: ["Ryan Gosling", "Harrison Ford"] },
  { id: 39, type: "movie", title: "Roma", year: 2018, overview: "A year in the life of a domestic worker for a middle-class family in 1970s Mexico City, quietly reckoning with loss and class.", genres: ["Drama", "Historical"], rating: 7.7, voteCount: 6800, popularity: 48, language: "Spanish", originalLanguage: "es", runtime: 135, director: "Alfonso Cuarón", cast: ["Yalitza Aparicio"] },
  { id: 40, type: "tv", title: "Attack on Titan", year: 2013, overview: "Humanity's last cities hide behind massive walls to survive against man-eating giants, until the walls are breached.", genres: ["Animation", "Action", "Fantasy", "Drama"], rating: 9.0, voteCount: 15500, popularity: 86, language: "Japanese", originalLanguage: "ja", seasons: 4, episodes: 94, director: "Tetsuro Araki", cast: [] },
  { id: 41, type: "movie", title: "Inception", year: 2010, overview: "A thief who steals secrets through dream infiltration is offered a chance at redemption if he can plant an idea instead.", genres: ["Sci-Fi", "Action", "Thriller"], rating: 8.8, voteCount: 35000, popularity: 91, language: "English", originalLanguage: "en", runtime: 148, director: "Christopher Nolan", cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"] },
  { id: 42, type: "movie", title: "Nomadland", year: 2020, overview: "After losing everything in the recession, a woman embarks on a journey through the American West living as a modern-day nomad.", genres: ["Drama"], rating: 7.4, voteCount: 4200, popularity: 42, language: "English", originalLanguage: "en", runtime: 108, director: "Chloé Zhao", cast: ["Frances McDormand"] },
  { id: 43, type: "tv", title: "The Bear", year: 2022, overview: "A young chef returns home to run his family's chaotic Chicago sandwich shop after a family tragedy.", genres: ["Comedy", "Drama"], rating: 8.6, voteCount: 6200, popularity: 72, language: "English", originalLanguage: "en", seasons: 3, episodes: 28, director: "Christopher Storer", cast: ["Jeremy Allen White"] },
  { id: 44, type: "movie", title: "Django Unchained", year: 2012, overview: "A freed slave partners with a bounty hunter to track down criminals across the antebellum South and rescue his wife.", genres: ["Western", "Drama"], rating: 8.4, voteCount: 24000, popularity: 79, language: "English", originalLanguage: "en", runtime: 165, director: "Quentin Tarantino", cast: ["Jamie Foxx", "Christoph Waltz"] },
  { id: 45, type: "movie", title: "Howl's Moving Castle", year: 2004, overview: "A young woman cursed with old age seeks refuge in the walking castle of an enigmatic and powerful wizard.", genres: ["Animation", "Fantasy", "Romance", "Family"], rating: 8.2, voteCount: 9800, popularity: 63, language: "Japanese", originalLanguage: "ja", runtime: 119, director: "Hayao Miyazaki", cast: ["Chieko Baisho"] },
  { id: 46, type: "tv", title: "Peaky Blinders", year: 2013, overview: "A crime family led by an ambitious patriarch fights for power in post-WWI Birmingham, England.", genres: ["Crime", "Drama", "Historical"], rating: 8.8, voteCount: 15800, popularity: 80, language: "English", originalLanguage: "en", seasons: 6, episodes: 36, director: "Steven Knight", cast: ["Cillian Murphy"] },
  { id: 47, type: "movie", title: "A Silent Voice", year: 2016, overview: "A former bully seeks redemption by reconnecting with the deaf classmate he once tormented years earlier.", genres: ["Animation", "Drama", "Romance"], rating: 8.1, voteCount: 6600, popularity: 44, language: "Japanese", originalLanguage: "ja", runtime: 130, director: "Naoko Yamada", cast: [] },
  { id: 48, type: "movie", title: "The Bourne Identity", year: 2002, overview: "A man with no memory of his past discovers he possesses lethal skills as shadowy agencies hunt him down.", genres: ["Action", "Thriller"], rating: 7.9, voteCount: 11000, popularity: 61, language: "English", originalLanguage: "en", runtime: 119, director: "Doug Liman", cast: ["Matt Damon"] },
  { id: 49, type: "tv", title: "Cosmos: A Spacetime Odyssey", year: 2014, overview: "A cinematic voyage through the universe, tracing the discoveries that changed how humanity understands its place in the cosmos.", genres: ["Documentary", "Sci-Fi"], rating: 9.3, voteCount: 5400, popularity: 47, language: "English", originalLanguage: "en", seasons: 1, episodes: 13, director: "Ann Druyan", cast: ["Neil deGrasse Tyson"] },
  { id: 50, type: "movie", title: "Eternal Sunshine of the Spotless Mind", year: 2004, overview: "A heartbroken man undergoes a procedure to erase memories of his ex, only to relive their romance in reverse.", genres: ["Romance", "Sci-Fi", "Drama"], rating: 8.3, voteCount: 15000, popularity: 66, language: "English", originalLanguage: "en", runtime: 108, director: "Michel Gondry", cast: ["Jim Carrey", "Kate Winslet"] },
  { id: 51, type: "movie", title: "Train to Busan", year: 2016, overview: "Passengers on a high-speed train to Busan fight to survive as a zombie outbreak spreads car by car.", genres: ["Horror", "Action", "Thriller"], rating: 7.6, voteCount: 8300, popularity: 64, language: "Korean", originalLanguage: "ko", runtime: 118, director: "Yeon Sang-ho", cast: ["Gong Yoo"] },
  { id: 52, type: "movie", title: "Big Hero 6", year: 2014, overview: "A young robotics prodigy and his inflatable healthcare companion form a team of unlikely heroes to save their city.", genres: ["Animation", "Family", "Action", "Comedy"], rating: 7.8, voteCount: 12000, popularity: 62, language: "English", originalLanguage: "en", runtime: 102, director: "Don Hall, Chris Williams", cast: ["Scott Adsit"] },
  { id: 53, type: "tv", title: "Sherlock", year: 2010, overview: "A consulting detective and his loyal companion solve London's most baffling crimes with startling deductive brilliance.", genres: ["Mystery", "Crime", "Drama"], rating: 9.1, voteCount: 14200, popularity: 74, language: "English", originalLanguage: "en", seasons: 4, episodes: 13, director: "Steven Moffat, Mark Gatiss", cast: ["Benedict Cumberbatch", "Martin Freeman"] },
  { id: 54, type: "movie", title: "Anatomy of a Fall", year: 2023, overview: "A writer becomes the prime suspect in her husband's death, and their son must confront the truth during her trial.", genres: ["Drama", "Mystery"], rating: 7.7, voteCount: 2600, popularity: 40, language: "French", originalLanguage: "fr", runtime: 152, director: "Justine Triet", cast: ["Sandra Hüller"] },
  { id: 55, type: "movie", title: "Oppenheimer", year: 2023, overview: "The story of the physicist who led the Manhattan Project and the moral reckoning that followed the atomic bomb's creation.", genres: ["Drama", "Historical", "Thriller"], rating: 8.3, voteCount: 12000, popularity: 88, language: "English", originalLanguage: "en", runtime: 180, director: "Christopher Nolan", cast: ["Cillian Murphy", "Emily Blunt"] },
  { id: 56, type: "tv", title: "Avatar: The Last Airbender", year: 2005, overview: "A young monk who can control all four elements must master his powers and end a century-long war.", genres: ["Animation", "Fantasy", "Adventure", "Family"], rating: 9.2, voteCount: 11500, popularity: 77, language: "English", originalLanguage: "en", seasons: 3, episodes: 61, director: "Michael Dante DiMartino, Bryan Konietzko", cast: [] },
  { id: 57, type: "movie", title: "The Grand Seduction", year: 2013, overview: "A struggling fishing village conspires to convince a big-city doctor to move in and save their fading community.", genres: ["Comedy", "Drama"], rating: 7.2, voteCount: 900, popularity: 20, language: "English", originalLanguage: "en", runtime: 113, director: "Don McKellar", cast: ["Brendan Gleeson"] },
  { id: 58, type: "movie", title: "Prisoners", year: 2013, overview: "When his daughter and her friend go missing, a desperate father takes matters into his own hands while a detective races to find the truth.", genres: ["Thriller", "Crime", "Mystery"], rating: 8.1, voteCount: 15000, popularity: 67, language: "English", originalLanguage: "en", runtime: 153, director: "Denis Villeneuve", cast: ["Hugh Jackman", "Jake Gyllenhaal"] },
  { id: 59, type: "tv", title: "Ted Lasso", year: 2020, overview: "An optimistic American football coach is hired to manage a struggling English soccer club he knows nothing about.", genres: ["Comedy", "Drama"], rating: 8.8, voteCount: 8600, popularity: 71, language: "English", originalLanguage: "en", seasons: 3, episodes: 34, director: "Bill Lawrence, Jason Sudeikis", cast: ["Jason Sudeikis"] },
  { id: 60, type: "movie", title: "WALL·E", year: 2008, overview: "A lonely trash-compacting robot on an abandoned Earth falls for a sleek probe sent to find signs of life.", genres: ["Animation", "Sci-Fi", "Family", "Adventure"], rating: 8.4, voteCount: 17000, popularity: 74, language: "English", originalLanguage: "en", runtime: 98, director: "Andrew Stanton", cast: [] },
  { id: 61, type: "movie", title: "Gladiator", year: 2000, overview: "A betrayed Roman general rises through the ranks of gladiatorial combat to seek vengeance against the corrupt emperor.", genres: ["Action", "Drama", "Historical"], rating: 8.5, voteCount: 18000, popularity: 78, language: "English", originalLanguage: "en", runtime: 155, director: "Ridley Scott", cast: ["Russell Crowe", "Joaquin Phoenix"] },
  { id: 62, type: "movie", title: "Moonlight", year: 2016, overview: "A young Black man's coming-of-age in three chapters, growing up in Miami while grappling with identity and sexuality.", genres: ["Drama"], rating: 7.4, voteCount: 6700, popularity: 45, language: "English", originalLanguage: "en", runtime: 111, director: "Barry Jenkins", cast: ["Trevante Rhodes"] },
  { id: 63, type: "tv", title: "The Last Dance", year: 2020, overview: "An inside account of Michael Jordan and the Chicago Bulls' final championship season, told through archival footage and interviews.", genres: ["Documentary"], rating: 9.1, voteCount: 5200, popularity: 55, language: "English", originalLanguage: "en", seasons: 1, episodes: 10, director: "Jason Hehir", cast: ["Michael Jordan"] },
  { id: 64, type: "movie", title: "A Quiet Place", year: 2018, overview: "A family must live in near-total silence to avoid drawing the attention of blind creatures that hunt by sound.", genres: ["Horror", "Thriller", "Sci-Fi"], rating: 7.5, voteCount: 14000, popularity: 68, language: "English", originalLanguage: "en", runtime: 90, director: "John Krasinski", cast: ["Emily Blunt", "John Krasinski"] },
  { id: 65, type: "tv", title: "Band of Brothers", year: 2001, overview: "The story of Easy Company's paratroopers from training through the end of World War II in Europe.", genres: ["War", "Historical", "Drama"], rating: 9.4, voteCount: 11000, popularity: 62, language: "English", originalLanguage: "en", seasons: 1, episodes: 10, director: "Steven Spielberg, Tom Hanks", cast: ["Damian Lewis"] },
  { id: 66, type: "movie", title: "The Secret in Their Eyes", year: 2009, overview: "A retired legal counselor writes a novel based on an unsolved murder case that has haunted him for decades.", genres: ["Mystery", "Drama", "Romance"], rating: 8.2, voteCount: 3400, popularity: 30, language: "Spanish", originalLanguage: "es", runtime: 129, director: "Juan José Campanella", cast: ["Ricardo Darín"] },
  { id: 67, type: "movie", title: "Booksmart", year: 2019, overview: "Two academically driven best friends try to cram four years of fun into one wild night before graduation.", genres: ["Comedy"], rating: 7.1, voteCount: 5300, popularity: 42, language: "English", originalLanguage: "en", runtime: 105, director: "Olivia Wilde", cast: ["Kaitlyn Dever", "Beanie Feldstein"] },
  { id: 68, type: "tv", title: "House of the Dragon", year: 2022, overview: "Two hundred years before the fall of King's Landing, House Targaryen tears itself apart in a war for succession.", genres: ["Fantasy", "Drama", "Action"], rating: 8.4, voteCount: 9200, popularity: 83, language: "English", originalLanguage: "en", seasons: 2, episodes: 18, director: "Ryan Condal, George R.R. Martin", cast: ["Emma D'Arcy", "Matt Smith"] },
  { id: 69, type: "movie", title: "Cinema Paradiso", year: 1988, overview: "A filmmaker recalls his childhood friendship with the projectionist at his small Sicilian town's beloved movie theater.", genres: ["Drama", "Romance"], rating: 8.5, voteCount: 4600, popularity: 33, language: "Italian", originalLanguage: "it", runtime: 155, director: "Giuseppe Tornatore", cast: ["Philippe Noiret"] },
  { id: 70, type: "movie", title: "No Country for Old Men", year: 2007, overview: "A hunter stumbles onto a drug deal gone wrong and the fortune left behind, drawing a relentless killer onto his trail.", genres: ["Crime", "Thriller", "Western"], rating: 8.2, voteCount: 17000, popularity: 69, language: "English", originalLanguage: "en", runtime: 122, director: "Joel Coen, Ethan Coen", cast: ["Javier Bardem", "Tommy Lee Jones"] },
  { id: 71, type: "tv", title: "Hunter x Hunter", year: 2011, overview: "A young boy sets out to become a licensed Hunter and find his estranged father, uncovering dangers far greater than expected.", genres: ["Animation", "Adventure", "Fantasy"], rating: 9.0, voteCount: 6300, popularity: 58, language: "Japanese", originalLanguage: "ja", seasons: 1, episodes: 148, director: "Hiroshi Kōjina", cast: [] },
  { id: 72, type: "movie", title: "Little Miss Sunshine", year: 2006, overview: "A dysfunctional family piles into a broken-down van for a cross-country trip to get their daughter to a beauty pageant.", genres: ["Comedy", "Drama", "Family"], rating: 7.8, voteCount: 8900, popularity: 48, language: "English", originalLanguage: "en", runtime: 101, director: "Jonathan Dayton, Valerie Faris", cast: ["Abigail Breslin", "Steve Carell"] },

  // ---------------- Egyptian movies & series ----------------
  { id: 73, type: "movie", title: "الإرهاب والكباب", year: 1992, overview: "موظف بسيط يضطر للتعامل مع الروتين الحكومي المعقد، فتتصاعد الأمور حتى يجد نفسه في مواجهة غير متوقعة داخل مبنى المحافظة.", genres: ["Comedy", "Drama"], rating: 8.2, voteCount: 1200, popularity: 55, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 100, director: "شريف عرفة", cast: ["عادل إمام"] },
  { id: 74, type: "movie", title: "الكيت كات", year: 1991, overview: "شيخ ضرير في حي شعبي بالقاهرة يواجه تحديات الحياة اليومية بروح ساخرة وحكمة خاصة، وسط علاقات الجيران وأزماتهم.", genres: ["Drama", "Comedy"], rating: 8.0, voteCount: 900, popularity: 42, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 100, director: "داود عبد السيد", cast: ["محمود عبد العزيز"] },
  { id: 75, type: "movie", title: "إسماعيلية رايح جاي", year: 1997, overview: "شابان من الإسماعيلية يجدان نفسيهما في مأزق كوميدي متصاعد بعد سلسلة من سوء الفهم والمواقف الطريفة.", genres: ["Comedy"], rating: 7.6, voteCount: 800, popularity: 48, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 100, director: "كريم ضياء الدين", cast: ["محمد هنيدي"] },
  { id: 76, type: "movie", title: "اللمبي", year: 2002, overview: "شاب بسيط من حي شعبي يخوض مغامرات كوميدية غير متوقعة تقلب حياته رأسًا على عقب.", genres: ["Comedy"], rating: 7.3, voteCount: 950, popularity: 50, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 100, director: "وائل إحسان", cast: ["محمد سعد"] },
  { id: 77, type: "movie", title: "عمارة يعقوبيان", year: 2006, overview: "قصص متشابكة لسكان عمارة قديمة وسط القاهرة، تكشف طبقات المجتمع المصري وتناقضاته عبر شخصيات متعددة.", genres: ["Drama"], rating: 7.8, voteCount: 3800, popularity: 62, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 172, director: "مروان حامد", cast: ["عادل إمام", "نور الشريف", "يسرا"] },
  { id: 78, type: "movie", title: "حسن ومرقص", year: 2008, overview: "رجلان من دينين مختلفين يضطران لتبديل هويتيهما هربًا من التطرف، فتتشابك حياتاهما في مواقف إنسانية وكوميدية.", genres: ["Comedy", "Drama"], rating: 7.2, voteCount: 700, popularity: 40, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 128, director: "عمر عبد العزيز", cast: ["عادل إمام", "عمر الشريف"] },
  { id: 79, type: "movie", title: "خللي بالك من زوزو", year: 1972, overview: "فتاة جامعية تعمل راقصة سرًا لإعالة أسرتها، وتجد نفسها بين حلم الحب وخوفها من انكشاف سرها.", genres: ["Musical", "Romance", "Drama"], rating: 7.9, voteCount: 600, popularity: 38, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 137, director: "حسن الإمام", cast: ["سعاد حسني"] },
  { id: 80, type: "movie", title: "الأرض", year: 1970, overview: "فلاحون في قرية مصرية يقاومون محاولات الإقطاعي الاستيلاء على أراضيهم، في ملحمة عن الكرامة والتمسك بالجذور.", genres: ["Drama", "Historical"], rating: 8.4, voteCount: 500, popularity: 30, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 130, director: "يوسف شاهين", cast: ["محمود المليجي"] },
  { id: 81, type: "movie", title: "عسل أسود", year: 2010, overview: "مصري أمريكي الجنسية يعود لوطنه بعد غياب طويل، فيصطدم بواقع مختلف تمامًا عما كان يتخيله.", genres: ["Comedy", "Drama"], rating: 7.4, voteCount: 1100, popularity: 52, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 129, director: "خالد مرعي", cast: ["أحمد حلمي"] },
  { id: 82, type: "movie", title: "ولاد رزق", year: 2015, overview: "ثلاثة إخوة من حي شعبي يخططون لسرقة كبرى تغير مجرى حياتهم، وسط مطاردات ومفاجآت متلاحقة.", genres: ["Action", "Comedy", "Crime"], rating: 7.5, voteCount: 1400, popularity: 58, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 128, director: "طارق العريان", cast: ["أحمد عز", "كريم محمود عبد العزيز", "أحمد الفيشاوي"] },
  { id: 83, type: "movie", title: "الفيل الأزرق", year: 2014, overview: "طبيب نفسي يعود للعمل في مستشفى الأمراض العقلية ليواجه لغزًا غامضًا يهدد عقله وحياته.", genres: ["Thriller", "Mystery", "Fantasy"], rating: 7.7, voteCount: 1600, popularity: 60, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 170, director: "مروان حامد", cast: ["كريم عبد العزيز"] },
  { id: 84, type: "movie", title: "الجزيرة", year: 2007, overview: "زعيم عصابة مخدرات يسيطر على جزيرة نائية بجنوب مصر، حتى يقرر ضابط شاب مواجهته مهما كلفه الأمر.", genres: ["Action", "Crime", "Drama"], rating: 7.6, voteCount: 1000, popularity: 46, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 160, director: "شريف عرفة", cast: ["أحمد السقا"] },
  { id: 85, type: "movie", title: "هيبتا", year: 2016, overview: "سبع قصص حب متوازية تتقاطع خيوطها لتكشف أوجهًا مختلفة للعلاقات العاطفية في المجتمع المصري المعاصر.", genres: ["Romance", "Drama"], rating: 6.9, voteCount: 650, popularity: 44, language: "Arabic", originalLanguage: "ar", country: "EG", runtime: 128, director: "هادي الباجوري", cast: ["أمير كرارة"] },

  { id: 86, type: "tv", title: "الاختيار", year: 2020, overview: "دراما تتناول قصصًا مستوحاة من الواقع عن ضباط الجيش المصري ومواقف مفصلية خلال فترات حساسة من تاريخ البلاد الحديث.", genres: ["Drama", "War", "Historical"], rating: 8.6, voteCount: 900, popularity: 64, language: "Arabic", originalLanguage: "ar", country: "EG", seasons: 3, episodes: 45, director: "بيتر ميمي", cast: ["كريم عبد العزيز", "أمير كرارة", "أحمد عز"] },
  { id: 87, type: "tv", title: "سره الباتع", year: 2018, overview: "امرأة قوية الإرادة تدير عائلتها وأعمالها في الصعيد وسط صراعات النفوذ والثأر والتقاليد المتوارثة.", genres: ["Drama"], rating: 7.9, voteCount: 500, popularity: 45, language: "Arabic", originalLanguage: "ar", country: "EG", seasons: 1, episodes: 30, cast: ["يسرا"] },
  { id: 88, type: "tv", title: "جراند أوتيل", year: 2016, overview: "أسرار وصراعات نفوذ تدور أحداثها داخل فندق فاخر في الإسكندرية بمطلع القرن العشرين.", genres: ["Drama", "Mystery", "Historical"], rating: 7.5, voteCount: 400, popularity: 40, language: "Arabic", originalLanguage: "ar", country: "EG", seasons: 1, episodes: 30, cast: ["يسرا", "كريم قاسم"] },
  { id: 89, type: "tv", title: "نسر الصعيد", year: 2020, overview: "شاب من الصعيد يشق طريقه وسط صراعات النفوذ والثأر التقليدي ليصبح أحد أقوى الرجال في منطقته.", genres: ["Drama", "Action"], rating: 7.3, voteCount: 550, popularity: 47, language: "Arabic", originalLanguage: "ar", country: "EG", seasons: 1, episodes: 30, cast: ["محمد رمضان"] },
  { id: 90, type: "tv", title: "أبو عمر المصري", year: 2021, overview: "ضابط مخابرات مصري يتخفى في مهمة استخباراتية حساسة تتشابك فيها الكوميديا مع الإثارة والتشويق.", genres: ["Comedy", "Thriller"], rating: 8.0, voteCount: 600, popularity: 53, language: "Arabic", originalLanguage: "ar", country: "EG", seasons: 1, episodes: 15, cast: ["أحمد أمين"] },
  { id: 91, type: "tv", title: "لام شمسية", year: 2016, overview: "امرأة تخوض رحلة معقدة للبحث عن ابنها المفقود، تكشف خلالها شبكة من الأسرار العائلية والاجتماعية.", genres: ["Drama", "Mystery"], rating: 7.6, voteCount: 350, popularity: 36, language: "Arabic", originalLanguage: "ar", country: "EG", seasons: 1, episodes: 30, cast: ["منة شلبي"] },
];

export function normalizeRaw(r: RawItem): MediaItem {
  return {
    id: r.id,
    type: r.type,
    title: r.title,
    year: r.year,
    overview: r.overview,
    // No API key set: we intentionally avoid guessing real TMDB image hashes.
    // A designed placeholder (see PosterArt component) is used instead of a real image.
    posterPath: null,
    backdropPath: null,
    rating: r.rating,
    voteCount: r.voteCount,
    popularity: r.popularity,
    genres: r.genres,
    language: r.language,
    originalLanguage: r.originalLanguage,
    country: r.country ?? null,
    runtime: r.runtime ?? null,
    numberOfSeasons: r.seasons ?? null,
    numberOfEpisodes: r.episodes ?? null,
    moods: moodsFromGenres(r.genres),
    director: r.director,
    cast: r.cast,
    trailerKey: null,
  };
}

export const FALLBACK_CATALOG: MediaItem[] = RAW_CATALOG.map(normalizeRaw);

export function fallbackById(type: MediaType, id: number): MediaItem | undefined {
  return FALLBACK_CATALOG.find((m) => m.type === type && m.id === id);
}
